server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/users/**
        - id: categories-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/categories/**
        - id: defining-themes-service
          uri: http://localhost:8030
          predicates:
            - Path=/api/v1/defining-themes/**