version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/client"
    schedule:
      interval: "monthly"
    groups:
      client-updates:
        patterns:
          - "*"
    ignore:
      - dependency-name: "androidx.compose:compose-bom"          # fixed due to using Icons class

  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "monthly"
    groups:
      server-updates:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.springframework.cloud:spring-cloud-dependencies"    # fixed due to Spring Boot 4.0.0
      - dependency-name: "org.springframework.kafka:spring-kafka"                 # fixed due to Spring Boot 4.0.0
