management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,shutdown

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5433/social_dating_db

services:
  gateway:
    host: localhost
  users:
    host: localhost
  categories:
    host: localhost
  defining-themes:
    host: localhost
  statements:
    host: localhost
