spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5435/defining_themes_db
    username: ${POSTGRES_DEFINING_THEMES_USER}
    password: ${POSTGRES_DEFINING_THEMES_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9093