spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5433/users_db
    username: ${POSTGRES_USERS_USER}
    password: ${POSTGRES_USERS_PASSWORD}