server:
  port: 8010

spring:
  application:
    name: users-service
  datasource:
    generate-unique-name: false
    name: users-service
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
