management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,shutdown

security:
  whitelist:
    - /users/auth/**
    - /actuator/health
    - /actuator/shutdown
    - /users/v3/api-docs

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5433/social_dating_db