server:
  port: 8010

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: users_user
    password: users_password
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
