server:
  port: ${services.users.port}

security:
  whitelist:
    - /users/auth/**
    - /actuator/health
    - /actuator/shutdown
    - /users/v3/api-docs

springdoc:
  api-docs:
    path: /users/v3/api-docs

spring:
  config:
    import: classpath:application-common.yml
  application:
    name: users-service
  datasource:
    hikari:
      connection-init-sql: set search_path to users_schema
  jpa:
    properties:
      hibernate:
        default_schema: users_schema
