spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5436/statements_db
    username: ${POSTGRES_STATEMENTS_USER}
    password: ${POSTGRES_STATEMENTS_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9093