security:
  whitelist:
    - /actuator/**
    - /api/v1/categories/**
    - /api/v1/categories/users/**

spring:
  web:
    locale: en
  datasource:
    url: jdbc:h2:mem:categories-db-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: never
