spring:
  datasource:
    generate-unique-name: false
    name: categories-service-test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
