name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test and Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        working-directory: client
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: client
        run: ./gradlew build

      - name: Upload Unit tests report
        uses: actions/upload-artifact@v4
        with:
          name: unit_tests_report
          working-directory: client
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Run Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: client
          api-level: 35
          script: |
            ./gradlew connectedAndroidTest

      - name: Upload Instrumented tests report
        uses: actions/upload-artifact@v4
        with:
          name: instrumented_tests_report
          working-directory: client
          path: app/build/reports/androidTests/connected/debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: social-dating.apk
          working-directory: client
          path: app/build/outputs/apk/debug/app-debug.apk